language: python
python:
  - "3.6"
install:
  - pip install pip-tools
  - pip-compile --output-file ~/requirements-dev.txt requirements/requirements-dev.in
  - pip install -r ~/requirements-dev.txt
script: python -m pytest