service: twitter-bot

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 60
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "dynamodb:GetItem"
       - "dynamodb:PutItem"
       - "dynamodb:BatchWriteItem"
     Resource: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/bills"
  -  Effect: "Allow"
     Action:
       - "secretsmanager:GetSecretValue"
     Resource:
       - "arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:Twitter-*"


package:
  exclude:
    - .venv/**
    - node_modules/**
    - .git/**
    - '*.pyc'

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-plugin-additional-stacks

custom:
  pythonRequirements:
    dockerizePip: non-linux
  additionalStacks:
    permanent:
      Resources:
        UsersDynamoDBTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: bills
            AttributeDefinitions:
              - AttributeName: bill_id
                AttributeType: S
            KeySchema:
              - AttributeName: bill_id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

functions:
  tweet:
    handler: tweet/handler.call
    events:
      - schedule:
          rate: rate(5 minute)
