service: twitter-bot

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource: "arn:aws:s3:::what-rahm-wants/*"
  -  Effect: "Allow"
     Action:
       - "secretsmanager:GetSecretValue"
     Resource:
       - "arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:Twitter-2gvVS8"

package:
  exclude:
    - .venv/**
    - node_modules/**
    - .git/**
    - '*.pyc'

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  tweet:
    handler: handler.call
    timeout: 60
    events:
      - s3:
          bucket: what-rahm-wants
          event: s3:ObjectCreated:*
          rules:
            - prefix: events/

